export const themes = [
  {
    name: 'Cornflower Blue',
    id: 'cornflower',
    fontFamily: { heading: 'Space Grotesk', body: 'DM Sans' },
    headingWeight: 700,
    colors: {
      primary: '#3b82f6',
      accent: '#22d3ee',
      background: '#ffffff',
      surface: '#eff6ff',
      border: '#dbeafe',
      text: '#1e3a8a',
      textMuted: '#64748b',
    },
  },
  {
    name: 'Cosmos',
    id: 'cosmos',
    fontFamily: { heading: 'Outfit', body: 'DM Sans' },
    headingWeight: 700,
    colors: {
      primary: '#7c3aed',
      accent: '#f59e0b',
      background: '#ffffff',
      surface: '#f5f3ff',
      border: '#e9d5ff',
      text: '#3b0764',
      textMuted: '#7c6a9e',
    },
  },
  {
    name: 'Microsoft Fluent',
    id: 'fluent',
    fontFamily: { heading: 'Outfit', body: 'DM Sans' },
    headingWeight: 700,
    colors: {
      primary: '#0078d4',
      accent: '#ffb900',
      background: '#ffffff',
      surface: '#f3f2f1',
      border: '#e1dfdd',
      text: '#201f1e',
      textMuted: '#605e5c',
    },
  },
  {
    name: 'Dalibio',
    id: 'dalibio',
    fontFamily: { heading: 'Cormorant Garamond', body: 'Outfit' },
    headingWeight: 700,
    colors: {
      primary: '#c2410c',
      accent: '#22d3ee',
      background: '#ffffff',
      surface: '#f5f5ff',
      border: '#e0e0f5',
      text: '#1e1b4b',
      textMuted: '#6b6b9a',
    },
  },
  {
    name: 'Noir',
    id: 'noir',
    fontFamily: { heading: 'Sora', body: 'DM Sans' },
    headingWeight: 800,
    colors: {
      primary: '#18181b',
      accent: '#facc15',
      background: '#ffffff',
      surface: '#f4f4f5',
      border: '#e4e4e7',
      text: '#09090b',
      textMuted: '#71717a',
    },
  },
  {
    name: 'Terra',
    id: 'terra',
    fontFamily: { heading: 'Playfair Display', body: 'Source Sans 3' },
    headingWeight: 700,
    colors: {
      primary: '#b45309',
      accent: '#0d9488',
      background: '#fffbf5',
      surface: '#fef3e2',
      border: '#f3dfc2',
      text: '#451a03',
      textMuted: '#92662f',
    },
  },
  {
    name: 'Indigo',
    id: 'indigo',
    fontFamily: { heading: 'Clash Display', body: 'General Sans' },
    headingWeight: 700,
    colors: {
      primary: '#ea580c',
      accent: '#f43f5e',
      background: '#ffffff',
      surface: '#eef2ff',
      border: '#dce2fb',
      text: '#7c2d12',
      textMuted: '#6366a3',
    },
  },
  {
    name: 'Orbit',
    id: 'orbit',
    fontFamily: { heading: 'Space Grotesk', body: 'DM Sans' },
    headingWeight: 700,
    colors: {
      primary: '#7c3aed',
      accent: '#34d399',
      background: '#ffffff',
      surface: '#f5f3ff',
      border: '#e4defc',
      text: '#2e1065',
      textMuted: '#7c6a9e',
    },
  },
  {
    name: 'Midnight',
    id: 'midnight',
    fontFamily: { heading: 'Sora', body: 'Inter' },
    headingWeight: 700,
    colors: {
      primary: '#f8fafc',
      accent: '#22d3ee',
      background: '#0f172a',
      surface: '#1e293b',
      border: '#334155',
      text: '#e2e8f0',
      textMuted: '#94a3b8',
    },
  },
  {
    name: 'Cursive Notes',
    id: 'cursive',
    fontFamily: { heading: 'Segoe Script', body: 'Segoe Print' },
    headingWeight: 700,
    colors: {
      primary: '#4f46e5',
      accent: '#f59e0b',
      background: '#fffdf5',
      surface: '#eef2ff',
      border: '#e0e7ff',
      text: '#312e81',
      textMuted: '#6b7280',
    },
  },
  {
    name: 'Brush Script',
    id: 'brush',
    fontFamily: { heading: 'Brush Script MT', body: 'Comic Sans MS' },
    headingWeight: 700,
    colors: {
      primary: '#9a3412',
      accent: '#0f766e',
      background: '#fffaf5',
      surface: '#fef3e2',
      border: '#f3e0cc',
      text: '#431407',
      textMuted: '#8a6a4f',
    },
  },
  {
    name: 'Handwritten',
    id: 'handwritten',
    fontFamily: { heading: 'Lucida Handwriting', body: 'Comic Sans MS' },
    headingWeight: 700,
    colors: {
      primary: '#be185d',
      accent: '#7c3aed',
      background: '#ffffff',
      surface: '#fdf2f8',
      border: '#fbcfe8',
      text: '#500724',
      textMuted: '#9d6b85',
    },
  },
];

export const CURATED_LOOKUP = Object.fromEntries(
  themes.map((t) => [
    t.id,
    { name: t.name, colors: t.colors, fontFamily: t.fontFamily, headingWeight: t.headingWeight },
  ])
);

// Fonts offered in the per-presentation font picker. Includes the fonts the
// themes already use plus handwriting/cursive fonts that ship with Microsoft
// Office, so a picked font also holds up in the exported PPTX.
export const FONT_CHOICES = [
  { label: "Space Grotesk", value: "Space Grotesk" },
  { label: "DM Sans", value: "DM Sans" },
  { label: "Outfit", value: "Outfit" },
  { label: "Sora", value: "Sora" },
  { label: "Inter", value: "Inter" },
  { label: "Clash Display", value: "Clash Display" },
  { label: "General Sans", value: "General Sans" },
  { label: "Playfair Display", value: "Playfair Display" },
  { label: "Cormorant Garamond", value: "Cormorant Garamond" },
  { label: "Source Sans 3", value: "Source Sans 3" },
  { label: "Georgia", value: "Georgia" },
  { label: "Times New Roman", value: "Times New Roman" },
  { label: "Arial", value: "Arial" },
  { label: "Comic Sans MS", value: "Comic Sans MS" },
  { label: "Brush Script MT", value: "Brush Script MT" },
  { label: "Lucida Handwriting", value: "Lucida Handwriting" },
  { label: "Segoe Script", value: "Segoe Script" },
  { label: "Segoe Print", value: "Segoe Print" },
];
